//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMOB_IPS_BackOffice
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CIMOB_IPS_DBEntities : DbContext
    {
        public CIMOB_IPS_DBEntities()
            : base("name=CIMOB_IPS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Application_Institutions> Application_Institutions { get; set; }
        public virtual DbSet<Coordenator> Coordenator { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Help> Help { get; set; }
        public virtual DbSet<Institution> Institution { get; set; }
        public virtual DbSet<Mobility> Mobility { get; set; }
        public virtual DbSet<Nationality> Nationality { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Pending_Account> Pending_Account { get; set; }
        public virtual DbSet<Program> Program { get; set; }
        public virtual DbSet<Program_Type> Program_Type { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Technician> Technician { get; set; }
        public virtual DbSet<test_file> test_file { get; set; }
    }
}
