//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMOB_IPS_BackOffice
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Mobility
    {
        public long id_mobility { get; set; }
        public long id_application { get; set; }
        public long id_state { get; set; }
        public long id_responsible_technician { get; set; }
        public long id_outgoing_institution { get; set; }
        public System.DateTime begin_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Institution Institution { get; set; }
        public virtual Technician Technician { get; set; }
    }
}
