//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMOB_IPS_BackOffice
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Application = new ObservableCollection<Application>();
        }
    
        public long id_student { get; set; }
        public long id_account { get; set; }
        public long id_course { get; set; }
        public string name { get; set; }
        public long cc { get; set; }
        public long telephone { get; set; }
        public long id_nationality { get; set; }
        public int credits { get; set; }
        public long student_num { get; set; }
        public string gender { get; set; }
        public System.DateTime birth_date { get; set; }
        public string postal_code { get; set; }
        public string address { get; set; }
        public Nullable<short> door_number { get; set; }
        public string floor { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Application> Application { get; set; }
        public virtual Course Course { get; set; }
        public virtual Nationality Nationality { get; set; }
    }
}
